version: '3.9'
services:
  web:
    build: .
    command: ./wait-for-it.sh mysql:3306 -- ./docker-entrypoint.sh
    ports:
      - 8000:8000
    depends_on:
      - redis
      - postgres
    restart: on-failure
    volumes:
      - .:/app
  postgres:
    image: postgres:14.1-alpine
    ports:
      - 5433:5433
    restart: always
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:6.2-alpine
    ports:
      - 6379:6379
    restart: always
    volumes:
      - redisdata:/data
  celery:
    build: .
    command: celery -A project worker --loglevel=info
    depends_on:
      - redis
    volumes:
      - .:/app
  tests:
    build: .
    command: ./wait-for-it.sh postgres:5433 -- ptw
    depends_on:
      - redis
      - postgres
    tty: true
    volumes:
      - .:/app
volumes:
  postgres_data:
  redisdata:  