# Generated by Django 4.0.6 on 2022-07-28 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planitem',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
