# Generated by Django 4.0.6 on 2022-07-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_alter_freeplan_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500)),
                ('price', models.IntegerField()),
                ('plan_type', models.CharField(choices=[('onJoin', 'onjoin'), ('onPayment', 'onpayment'), ('onCard', 'oncard'), ('onReferralPayment', 'onreferralpayment'), ('onReferralCard', 'onreferralcard'), ('onReferralJoin', 'onreferraljoin'), ('1month', 'onemonth'), ('3month', 'treemonth'), ('6month', 'sixmonth')], max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('slug', models.SlugField(max_length=500, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='FreePlan',
        ),
    ]
