# Generated by Django 4.0.6 on 2022-07-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0004_plan_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='plan_type',
            field=models.CharField(choices=[('onJoin free', 'onjoin'), ('onPayment free', 'onpayment'), ('onCard free', 'oncard'), ('onReferralPayment free', 'onreferralpayment'), ('onReferralCard free', 'onreferralcard'), ('onReferralJoin free', 'onreferraljoin'), ('1month', 'onemonth'), ('3month', 'treemonth'), ('6month', 'sixmonth')], max_length=100),
        ),
    ]
