# Generated by Django 4.0.6 on 2022-07-24 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0007_rename_sunbscribe_subscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='plan_type',
            field=models.CharField(choices=[('0', 'on Join 30 days free'), ('30', '1 month'), ('90', '3 months'), ('180', '6 months')], max_length=100),
        ),
    ]
